# Generated by Django 5.2 on 2025-04-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='客户编号')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名')),
                ('last_name', models.CharField(max_length=100, verbose_name='姓')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
    ]
