# Generated by Django 5.2 on 2025-04-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_salesheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesheader',
            name='currency',
            field=models.CharField(default='', max_length=3, verbose_name='货币'),
        ),
    ]
