# Generated by Django 5.2 on 2025-04-13 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_salesheader_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=50, verbose_name='电话')),
            ],
            options={
                'verbose_name': '模型基类',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dealer_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('no', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('category', models.SmallIntegerField(choices=[(1, '2S'), (2, '3S'), (3, '4S')], verbose_name='分类')),
            ],
            options={
                'verbose_name': '模型基类',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('no', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='经销商编号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
            ],
            options={
                'verbose_name': '模型基类',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '模型基类'},
        ),
        migrations.AlterModelOptions(
            name='salesheader',
            options={'verbose_name': '模型基类'},
        ),
        migrations.AddField(
            model_name='salesheader',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AddField(
            model_name='salesheader',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('no', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='经销商编号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('address', models.TextField(verbose_name='地址')),
                ('phone', models.CharField(max_length=50, verbose_name='电话')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('dealer_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.dealer_type', verbose_name='经销商类型')),
            ],
            options={
                'verbose_name': '模型基类',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('category', models.SmallIntegerField(choices=[(1, '房产'), (2, '机器设备'), (3, '运输工具'), (4, '电子产品'), (5, '办公设备'), (6, '土地')], verbose_name='资产类型')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.department', verbose_name='所属部门')),
            ],
        ),
    ]
