# Generated by Django 5.2 on 2025-04-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_admin_dealer_type_department_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='dealer_type',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='salesheader',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
    ]
