# Generated by Django 5.2 on 2025-04-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_admin_updated_at_alter_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesheader',
            name='payment_status',
            field=models.CharField(choices=[('paid', '已支付'), ('unpaid', '未支付')], default='unpaid', max_length=20, verbose_name='支付状态'),
        ),
        migrations.AddField(
            model_name='salesheader',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '打开'), (2, '完成'), (3, '取消')], default=1, verbose_name='状态'),
        ),
    ]
