# Generated by Django 5.2 on 2025-04-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_salesheader_payment_status_salesheader_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, default='', null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='no',
            field=models.CharField(max_length=10, unique=True, verbose_name='客户编号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='dealer_type',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dealer_type',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='dealer_type',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='dealer_type',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='salesheader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='salesheader',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='货币'),
        ),
        migrations.AlterField(
            model_name='salesheader',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='salesheader',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='salesheader',
            name='sales_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='销售日期'),
        ),
        migrations.AlterField(
            model_name='salesheader',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='salesheader',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
